### ISSUE TITLE
change license to MIT

### ISSUE THREAD

**Issue by frnandu** [haorendashu/nostrmo#2]
In order to contribute to a FOSS project and feel that whatever happens your contribution can later be used in a forked version,  GPL-3.0 license  is too restrictive to allow that. Better use MIT, which amethyst and primal both use. Please consider changing it, so contributors can feel more motivated to take part.

**Comment by sant0s12** [comment]
Bad take, GPL is better since it protects your contribution from ending up in closed source software.
